language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install: pip install -r requirements.txt
script: py.test
deploy:
  provider: pypi
  user: theaeolianmachine
  password:
    secure: K+lIh14fZr/YHoHkE5W7Z8o5kZmbg2X2PiFLYQibF3MJaiyySyEkSEXkrLK4gdXLLuWMBN4fTVeh848LFiUHzHNKoyTmgBSBtdQRvAqqlAAIeP9PIy70zoQ3AFQ8ajTG+reEE44FdpvMcfP1eboWZmFQ+V21XaQDTKLiyxr3DqM=
  on:
    tags: true
    repo: Asana/python-asana
    all_branches: true
  distributions: "sdist bdist_wheel"
